### ISSUE TITLE
fix broken link

### ISSUE THREAD

**Issue by scottdangelo** [IBM/monitor-ibm-cloud-pak-with-watson-openscale#21]
[Watson Machine Learning Add On for Cloud Pak for Data](https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_current/com.ibm.icpdata.doc/zen/admin/add-ons.html#add-ons__ai)
is broken.
IN prerequisites

**Comment by sandhya-nayak** [comment]
1. [Watson Machine Learning Add On for Cloud Pak for Data](https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_current/com.ibm.icpdata.doc/zen/admin/add-ons.html#add-ons__ai) needs to be added to prerequisites.

2. Watson OpenScale is mentioned twice in prerequisites (one of those links is broken)

3. Watson Machine Learning link in the first line of the ReadMe is broken.
